package mona.Small_Twitter.Users;

import org.springframework.web.bind.annotation.RequestParam;

public class Users {
    // Is user ID generated by  my database?
    private long system_user_id;
    private String userID;
    private String email;
    private String password;

    // Additional Parameter that the Users has the option
    private String birthday;
    private String address;

    //Constructors
    public Users(){
    }

    public Users(String userID, String email, String password) {
        this.userID = userID;
        this.email = email;
        this.password = password;
    }

    public Users(String email, String password) {
        this.email = email;
        this.password = password;
    }

    public Users(String userID, String email, String password, String birthday, String address) {
        this.userID = userID;
        this.email = email;
        this.password = password;
        this.birthday = birthday;
        this.address = address;
    }

    public Users(String email, String password, String birthday, String address) {
        this.email = email;
        this.password = password;
        this.birthday = birthday;
        this.address = address;
    }

    // Getter and Setter Pair for Java
    public long getSystem_user_id() {
        return system_user_id;
    }

    public String getUserID() {
        return userID;
    }

    public String getEmail() {
        return email;
    }

    public String getPassword() {
        return password;
    }

    public String getBirthday() {
        return birthday;
    }

    public String getAddress() {
        return address;
    }

    public void setSystem_user_id(long system_user_id) {
        this.system_user_id = system_user_id;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public String toString() {
        return "Users{" +
                "system_user_id=" + system_user_id +
                ", userID='" + userID + '\'' +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                ", birthday='" + birthday + '\'' +
                ", address='" + address + '\'' +
                '}';
    }
}
