package mona.Small_Twitter.Users;

public class Users {
    // Is user ID generated by  postgresql?
    private long system_user_id;
    private String userID;


    public Users(long system_user_id, String userID) {
        this.system_user_id = system_user_id;
        this.userID = userID;
    }

    public Users(String mona) {
        this.userID = userID;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    @Override
    public String toString() {
        return "Users{" +
                "userID='" + userID + '\'' +
                '}';
    }
}
